### ISSUE TITLE
launch_prime root variable no error

### ISSUE THREAD

**Issue by waltersma** [ansys/pyprimemesh#270]
Setting a parameter to define root for launching Ansys Prime Server returned no error even though parameter was not named correctly.

**Comment by ninad-kamat** [comment]
@waltersma The naming of parameters is kept open-ended intentionally to allow flexibility in certain environments such as notebooks. Would you want to have a check specifically for `prime_root` or since the client was never publicly released with this option, we can ignore it and close the issue? Current behavior is to ignore any arguments that are not used.

**Comment by waltersma** [comment]
@ninad-kamat closing as discussed.
